# Deploy using gitflow
#
# Basic idea:
# * Developers almost always patch to master first.
# * Releases happen on a branch
# * They can cherry-pick (or ffwd-merge, aka no-fault rebase) to releases
# * Once a release goes out it is tagged. Tags are on releases, these may or
#   may not be in a history.
#
# Where do deployments go:
# master -> develop01
# feature/* -> develop[X] after select
# release/* -> staging
# v* -> production after block & shout

env:
  AWS_ACCOUNT_ALIAS: common
  ENVIRONMENT_NAME: common
  DEPLOY_ENVIRONMENT_NAME: production
  TEST_ENVIRONMENT_NAME: develop02
  S3_HOSTNAME: demos.developer.virtru.com
  USE_NODE_12: true
  VIRTRU_ENV: develop02

steps:
  - label: ':chrome: E2E Tests: $TEST_ENVIRONMENT_NAME'
    command: buildkite-agent pipeline upload .buildkite/post.yml
